<?php
// Bootstrap WordPress
require_once('wp-load.php');

// Get Yoast frontend instance
if (class_exists('WPSEO_Frontend')) {
    $frontend = WPSEO_Frontend::get_instance();
    echo "Yoast frontend exists!\n";
    
    // Check if the current page is frontpage
    global $wp_query;
    $wp_query->is_home = false;
    $wp_query->is_front_page = true;
    
    // Set queried object to homepage post ID 4179
    $wp_query->queried_object = get_post(4179);
    $wp_query->queried_object_id = 4179;
    
    $title = $frontend->title( '' );
    $metadesc = $frontend->metadesc( false );
    
    echo "Title generated by Yoast: " . $title . "\n";
    echo "Meta Description generated by Yoast: " . $metadesc . "\n";
    
    // Let's check Yoast settings
    $wpseo_titles = get_option('wpseo_titles');
    echo "title-home-wpseo: " . ($wpseo_titles['title-home-wpseo'] ?? 'not set') . "\n";
    echo "metadesc-home-wpseo: " . ($wpseo_titles['metadesc-home-wpseo'] ?? 'not set') . "\n";
} else {
    echo "Yoast SEO is not active or class WPSEO_Frontend does not exist.\n";
}
